apiVersion: v2
name: jellyfin-db-sync
description: Bidirectional sync service for multiple Jellyfin instances

type: application
version: 0.0.5
appVersion: "0.0.5"

home: https://github.com/lnking81/jellyfin-db-sync
icon: https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/icon-transparent.svg

sources:
  - https://github.com/lnking81/jellyfin-db-sync

maintainers:
  - name: lnking81
    url: https://github.com/lnking81

keywords:
  - jellyfin
  - media
  - sync
  - plex
  - emby

annotations:
  artifacthub.io/category: media
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/lnking81/jellyfin-db-sync#readme
    - name: Source
      url: https://github.com/lnking81/jellyfin-db-sync
